# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e48346c7114307e736262804109f71b0"
name = "regional-upside-app"
application_url = "https://alberta-reid-wishlist-possibilities.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extensions-sandbox.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://alberta-reid-wishlist-possibilities.trycloudflare.com/auth/callback",
  "https://alberta-reid-wishlist-possibilities.trycloudflare.com/auth/shopify/callback",
  "https://alberta-reid-wishlist-possibilities.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
